In [44]:
from google.colab import files
import pandas as pd
import numpy as np
uploaded=files.upload()
df = pd.read_csv("/content/Indian_Employee_Data.csv")

Saving Indian_Employee_Data.csv to Indian_Employee_Data (9).csv

In [45]:
df.head()

,Employee_ID,Name,Age,Gender,Department,Position,Salary,Experience_Years,City,State,Education,Performance_Rating,Joining_Date,Projects_Completed,Overtime_Hours
0,EMP001,Rajesh Kumar,32.0,Male,Engineering,Senior Developer,850000.0,8.0,Bangalore,Karnataka,B.Tech,4.2,03/15/2016,12.0,45.0
1,EMP002,Priya Sharma,28.0,Female,Marketing,Marketing Manager,720000.0,5.0,Mumbai,Maharashtra,MBA,4.5,01/20/2019,8.0,32.0
2,EMP003,Amit Singh,35.0,Male,Finance,Financial Analyst,650000.0,10.0,Delhi,Delhi,CA,3.8,07/10/2014,15.0,28.0
3,EMP004,Sneha Patel,26.0,Female,NaN,HR Executive,480000.0,3.0,Ahmedabad,Gujarat,MBA,4.1,05/12/2021,6.0,20.0
4,EMP005,Vikram Reddy,40.0,Male,Engineering,Tech Lead,1200000.0,15.0,Hyderabad,Telangana,M.Tech,4.7,11/08/2009,25.0,55.0

In [46]:
df.tail()

,Employee_ID,Name,Age,Gender,Department,Position,Salary,Experience_Years,City,State,Education,Performance_Rating,Joining_Date,Projects_Completed,Overtime_Hours
44,EMP045,Neha Kapoor,28.0,Female,IT,Data Analyst,NaN,4.0,Bangalore,Karnataka,M.Sc,3.8,04/12/2020,6.0,29.0
45,EMP046,Amit Sharma,27.0,Male,IT,Junior Developer,650000.0,4.0,Delhi,NaN,B.Tech,4.5,08/20/2020,5.0,25.0
46,EMP047,Riya Gupta,32.0,Female,HR,HR Specialist,NaN,8.0,Mumbai,Maharashtra,MBA,NaN,11/03/2016,inf,42.0
47,EMP048,Rohit Bansal,36.0,Male,Finance,Senior Analyst,980000.0,12.0,Mumbai,Maharashtra,CA,4.9,03/20/2012,19.0,51.0
48,EMP049,Sneha Tiwari,25.0,Female,Sales,Sales Representative,inf,2.0,Kolkata,West Bengal,B.Com,3.6,05/14/2022,3.0,16.0

In [47]:
print(df.isnull().sum())

Employee_ID           0
Name                  0
Age                   2
Gender                0
Department            1
Position              1
Salary                5
Experience_Years      2
City                  0
State                 3
Education             0
Performance_Rating    4
Joining_Date          1
Projects_Completed    1
Overtime_Hours        1
dtype: int64

In [48]:
df.dropna()

,Employee_ID,Name,Age,Gender,Department,Position,Salary,Experience_Years,City,State,Education,Performance_Rating,Joining_Date,Projects_Completed,Overtime_Hours
0,EMP001,Rajesh Kumar,32.0,Male,Engineering,Senior Developer,850000.0,8.0,Bangalore,Karnataka,B.Tech,4.2,03/15/2016,12.0,45.0
1,EMP002,Priya Sharma,28.0,Female,Marketing,Marketing Manager,720000.0,5.0,Mumbai,Maharashtra,MBA,4.5,01/20/2019,8.0,32.0
2,EMP003,Amit Singh,35.0,Male,Finance,Financial Analyst,650000.0,10.0,Delhi,Delhi,CA,3.8,07/10/2014,15.0,28.0
4,EMP005,Vikram Reddy,40.0,Male,Engineering,Tech Lead,1200000.0,15.0,Hyderabad,Telangana,M.Tech,4.7,11/08/2009,25.0,55.0
5,EMP006,Kavya Nair,29.0,Female,Sales,Sales Executive,550000.0,4.0,Chennai,Tamil Nadu,B.Com,3.9,02/28/2020,inf,38.0
7,EMP008,Meera Joshi,27.0,Female,Design,UI/UX Designer,620000.0,4.0,Bangalore,Karnataka,B.Des,4.4,08/03/2020,7.0,25.0
9,EMP010,Anita Verma,38.0,Female,HR,HR Manager,950000.0,12.0,Gurgaon,Haryana,MBA,4.6,04/18/2012,18.0,48.0
10,EMP011,Suresh Iyer,42.0,Male,Engineering,Principal Engineer,1350000.0,18.0,Chennai,Tamil Nadu,M.Tech,4.8,01/25/2006,30.0,60.0
12,EMP013,Karan Chopra,30.0,Male,Sales,Sales Manager,780000.0,6.0,Mumbai,Maharashtra,MBA,4.2,06/22/2018,10.0,35.0
13,EMP014,Divya Rao,34.0,Female,Engineering,Data Scientist,950000.0,8.0,Bangalore,Karnataka,M.Sc,4.5,10/05/2016,14.0,40.0
16,EMP017,Deepak Kumar,39.0,Male,Engineering,Software Architect,1150000.0,14.0,Hyderabad,Telangana,M.Tech,4.6,02/12/2010,inf,52.0
17,EMP018,Sonia Kapoor,26.0,Female,Design,Graphic Designer,420000.0,3.0,Chandigarh,Punjab,B.Des,4.0,07/08/2021,5.0,18.0
19,EMP020,Nisha Pandey,29.0,Female,HR,Talent Acquisition Specialist,520000.0,4.0,Lucknow,Uttar Pradesh,MBA,4.2,09/25/2020,7.0,28.0
20,EMP021,Gaurav Mishra,37.0,Male,Engineering,Full Stack Developer,820000.0,10.0,Indore,Madhya Pradesh,B.Tech,4.3,05/16/2014,17.0,44.0
22,EMP023,Ashish Jain,28.0,Male,Finance,Investment Analyst,680000.0,5.0,Surat,Gujarat,CFA,4.1,08/14/2019,9.0,33.0
23,EMP024,Swati Agrawal,33.0,Female,Operations,Process Manager,720000.0,9.0,Nagpur,Maharashtra,B.Tech,4.0,03/28/2015,14.0,36.0
24,EMP025,Vishal Gupta,35.0,Male,Engineering,Machine Learning Engineer,1050000.0,9.0,Bangalore,Karnataka,M.Tech,4.7,09/10/2015,16.0,48.0
29,EMP030,Rajesh Verma,45.0,Male,Finance,CFO,1200000.0,inf,Bangalore,Karnataka,CA,4.9,02/28/2005,28.0,65.0
32,EMP033,Alok Mehta,52.0,Male,Operations,VP Operations,2000000.0,28.0,Hyderabad,Telangana,MBA,5.0,05/18/1996,45.0,inf
33,EMP034,Kavita Yadav,31.0,Female,IT,DevOps Engineer,inf,10.0,Pune,Maharashtra,B.Tech,4.0,12/07/2014,15.0,44.0
34,EMP035,Pankaj Mishra,24.0,Male,Marketing,Marketing Associate,-45000.0,2.0,Jaipur,Rajasthan,BBA,3.5,07/25/2022,3.0,18.0
35,EMP036,Deepika Roy,48.0,Female,Management,Director,3000000.0,30.0,Bangalore,Karnataka,MBA,5.0,03/12/1994,50.0,72.0
38,EMP039,Sameer Desai,37.0,Male,Finance,Finance Manager,1100000.0,15.0,Delhi,Delhi,CA,4.8,10/05/2009,22.0,58.0
40,EMP041,Vinod Iyer,55.0,Male,Management,CEO,5000000.0,35.0,Chennai,Tamil Nadu,MBA,5.0,01/15/1989,inf,80.0
41,EMP042,Anjali Saxena,23.0,Female,HR,HR Trainee,380000.0,3.0,Pune,Maharashtra,MBA,3.9,11/22/2021,2.0,12.0
42,EMP043,Manish Khanna,40.0,Male,Operations,Operations Head,1250000.0,18.0,Hyderabad,Telangana,B.Tech,4.7,07/08/2006,32.0,62.0
43,EMP044,Arjun Pandey,31.0,Male,IT,Software Engineer,750000.0,7.0,Jaipur,Rajasthan,B.Tech,4.4,06/15/2017,11.0,37.0
47,EMP048,Rohit Bansal,36.0,Male,Finance,Senior Analyst,980000.0,12.0,Mumbai,Maharashtra,CA,4.9,03/20/2012,19.0,51.0
48,EMP049,Sneha Tiwari,25.0,Female,Sales,Sales Representative,inf,2.0,Kolkata,West Bengal,B.Com,3.6,05/14/2022,3.0,16.0

In [50]:
df.fillna(0)

,Employee_ID,Name,Age,Gender,Department,Position,Salary,Experience_Years,City,State,Education,Performance_Rating,Joining_Date,Projects_Completed,Overtime_Hours
0,EMP001,Rajesh Kumar,32.0,Male,Engineering,Senior Developer,850000.0,8.0,Bangalore,Karnataka,B.Tech,4.2,03/15/2016,12.0,45.0
1,EMP002,Priya Sharma,28.0,Female,Marketing,Marketing Manager,720000.0,5.0,Mumbai,Maharashtra,MBA,4.5,01/20/2019,8.0,32.0
2,EMP003,Amit Singh,35.0,Male,Finance,Financial Analyst,650000.0,10.0,Delhi,Delhi,CA,3.8,07/10/2014,15.0,28.0
3,EMP004,Sneha Patel,26.0,Female,0,HR Executive,480000.0,3.0,Ahmedabad,Gujarat,MBA,4.1,05/12/2021,6.0,20.0
4,EMP005,Vikram Reddy,40.0,Male,Engineering,Tech Lead,1200000.0,15.0,Hyderabad,Telangana,M.Tech,4.7,11/08/2009,25.0,55.0
5,EMP006,Kavya Nair,29.0,Female,Sales,Sales Executive,550000.0,4.0,Chennai,Tamil Nadu,B.Com,3.9,02/28/2020,inf,38.0
6,EMP007,Arjun Gupta,31.0,Male,Engineering,DevOps Engineer,0.0,7.0,Pune,Maharashtra,B.Tech,4.3,09/14/2017,11.0,42.0
7,EMP008,Meera Joshi,27.0,Female,Design,UI/UX Designer,620000.0,4.0,Bangalore,Karnataka,B.Des,4.4,08/03/2020,7.0,25.0
8,EMP009,Rohit Agarwal,33.0,Male,Finance,0,580000.0,9.0,Kolkata,West Bengal,M.Com,3.7,12/01/2015,13.0,30.0
9,EMP010,Anita Verma,38.0,Female,HR,HR Manager,950000.0,12.0,Gurgaon,Haryana,MBA,4.6,04/18/2012,18.0,48.0
10,EMP011,Suresh Iyer,42.0,Male,Engineering,Principal Engineer,1350000.0,18.0,Chennai,Tamil Nadu,M.Tech,4.8,01/25/2006,30.0,60.0
11,EMP012,Pooja Malhotra,0.0,Female,Marketing,Digital Marketing Specialist,450000.0,2.0,Delhi,Delhi,BBA,4.0,03/10/2022,4.0,15.0
12,EMP013,Karan Chopra,30.0,Male,Sales,Sales Manager,780000.0,6.0,Mumbai,Maharashtra,MBA,4.2,06/22/2018,10.0,35.0
13,EMP014,Divya Rao,34.0,Female,Engineering,Data Scientist,950000.0,8.0,Bangalore,Karnataka,M.Sc,4.5,10/05/2016,14.0,40.0
14,EMP015,Manoj Tiwari,36.0,Male,Operations,Operations Manager,820000.0,0.0,Noida,Uttar Pradesh,B.Tech,4.1,08/30/2013,16.0,45.0
15,EMP016,Ritu Bansal,28.0,Female,Finance,Financial Planner,580000.0,5.0,Jaipur,0,MBA,3.9,11/15/2019,8.0,22.0
16,EMP017,Deepak Kumar,39.0,Male,Engineering,Software Architect,1150000.0,14.0,Hyderabad,Telangana,M.Tech,4.6,02/12/2010,inf,52.0
17,EMP018,Sonia Kapoor,26.0,Female,Design,Graphic Designer,420000.0,3.0,Chandigarh,Punjab,B.Des,4.0,07/08/2021,5.0,18.0
18,EMP019,Rahul Saxena,32.0,Male,Marketing,Product Manager,890000.0,7.0,Pune,Maharashtra,MBA,0.0,04/20/2017,12.0,38.0
19,EMP020,Nisha Pandey,29.0,Female,HR,Talent Acquisition Specialist,520000.0,4.0,Lucknow,Uttar Pradesh,MBA,4.2,09/25/2020,7.0,28.0
20,EMP021,Gaurav Mishra,37.0,Male,Engineering,Full Stack Developer,820000.0,10.0,Indore,Madhya Pradesh,B.Tech,4.3,05/16/2014,17.0,44.0
21,EMP022,Preeti Singh,31.0,Female,Sales,Regional Sales Head,950000.0,0.0,Bhopal,Madhya Pradesh,MBA,4.5,12/03/2016,13.0,46.0
22,EMP023,Ashish Jain,28.0,Male,Finance,Investment Analyst,680000.0,5.0,Surat,Gujarat,CFA,4.1,08/14/2019,9.0,33.0
23,EMP024,Swati Agrawal,33.0,Female,Operations,Process Manager,720000.0,9.0,Nagpur,Maharashtra,B.Tech,4.0,03/28/2015,14.0,36.0
24,EMP025,Vishal Gupta,35.0,Male,Engineering,Machine Learning Engineer,1050000.0,9.0,Bangalore,Karnataka,M.Tech,4.7,09/10/2015,16.0,48.0
25,EMP026,Arjun Pandey,0.0,Male,IT,Software Engineer,750000.0,7.0,Jaipur,Rajasthan,B.Tech,4.4,06/15/2017,11.0,37.0
26,EMP027,Neha Kapoor,28.0,Female,IT,Data Analyst,0.0,4.0,Bangalore,Karnataka,M.Sc,3.8,04/12/2020,6.0,29.0
27,EMP028,Amit Sharma,27.0,Male,IT,Junior Developer,650000.0,4.0,Delhi,0,B.Tech,4.5,08/20/2020,5.0,25.0
28,EMP029,Riya Gupta,32.0,Female,HR,HR Specialist,0.0,8.0,Mumbai,Maharashtra,MBA,3.8,11/03/2016,12.0,42.0
29,EMP030,Rajesh Verma,45.0,Male,Finance,CFO,1200000.0,inf,Bangalore,Karnataka,CA,4.9,02/28/2005,28.0,65.0
30,EMP031,Priya Singh,29.0,Female,IT,QA Engineer,720000.0,6.0,Kolkata,West Bengal,B.Tech,4.2,09/14/2018,0.0,33.0
31,EMP032,Sunil Kumar,26.0,Male,Sales,Sales Executive,500000.0,3.0,Chennai,Tamil Nadu,B.Com,0.0,01/10/2021,4.0,22.0
32,EMP033,Alok Mehta,52.0,Male,Operations,VP Operations,2000000.0,28.0,Hyderabad,Telangana,MBA,5.0,05/18/1996,45.0,inf
33,EMP034,Kavita Yadav,31.0,Female,IT,DevOps Engineer,inf,10.0,Pune,Maharashtra,B.Tech,4.0,12/07/2014,15.0,44.0
34,EMP035,Pankaj Mishra,24.0,Male,Marketing,Marketing Associate,-45000.0,2.0,Jaipur,Rajasthan,BBA,3.5,07/25/2022,3.0,18.0
35,EMP036,Deepika Roy,48.0,Female,Management,Director,3000000.0,30.0,Bangalore,Karnataka,MBA,5.0,03/12/1994,50.0,72.0
36,EMP037,Ramesh Patel,29.0,Male,IT,Backend Developer,720000.0,6.0,Kolkata,West Bengal,B.Tech,4.2,0,9.0,35.0
37,EMP038,Meera Nair,34.0,Female,HR,Senior HR Manager,820000.0,9.0,Kochi,Kerala,MBA,4.3,08/19/2015,14.0,0.0
38,EMP039,Sameer Desai,37.0,Male,Finance,Finance Manager,1100000.0,15.0,Delhi,Delhi,CA,4.8,10/05/2009,22.0,58.0
39,EMP040,Swati Joshi,29.0,Female,IT,Full Stack Developer,650000.0,5.0,Mumbai,Maharashtra,B.Tech,0.0,04/30/2019,8.0,31.0
40,EMP041,Vinod Iyer,55.0,Male,Management,CEO,5000000.0,35.0,Chennai,Tamil Nadu,MBA,5.0,01/15/1989,inf,80.0
41,EMP042,Anjali Saxena,23.0,Female,HR,HR Trainee,380000.0,3.0,Pune,Maharashtra,MBA,3.9,11/22/2021,2.0,12.0
42,EMP043,Manish Khanna,40.0,Male,Operations,Operations Head,1250000.0,18.0,Hyderabad,Telangana,B.Tech,4.7,07/08/2006,32.0,62.0
43,EMP044,Arjun Pandey,31.0,Male,IT,Software Engineer,750000.0,7.0,Jaipur,Rajasthan,B.Tech,4.4,06/15/2017,11.0,37.0
44,EMP045,Neha Kapoor,28.0,Female,IT,Data Analyst,0.0,4.0,Bangalore,Karnataka,M.Sc,3.8,04/12/2020,6.0,29.0
45,EMP046,Amit Sharma,27.0,Male,IT,Junior Developer,650000.0,4.0,Delhi,0,B.Tech,4.5,08/20/2020,5.0,25.0
46,EMP047,Riya Gupta,32.0,Female,HR,HR Specialist,0.0,8.0,Mumbai,Maharashtra,MBA,0.0,11/03/2016,inf,42.0
47,EMP048,Rohit Bansal,36.0,Male,Finance,Senior Analyst,980000.0,12.0,Mumbai,Maharashtra,CA,4.9,03/20/2012,19.0,51.0
48,EMP049,Sneha Tiwari,25.0,Female,Sales,Sales Representative,inf,2.0,Kolkata,West Bengal,B.Com,3.6,05/14/2022,3.0,16.0

In [52]:
print(df.isnull().sum())

Employee_ID           0
Name                  0
Age                   2
Gender                0
Department            1
Position              1
Salary                5
Experience_Years      2
City                  0
State                 3
Education             0
Performance_Rating    4
Joining_Date          1
Projects_Completed    1
Overtime_Hours        1
dtype: int64

In [53]:
print(df.duplicated().sum())

0

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         49 non-null     object
 1   Name                49 non-null     object
 2   Age                 47 non-null     float64
 3   Gender              49 non-null     object
 4   Department          48 non-null     object
 5   Position            48 non-null     object
 6   Salary              44 non-null     float64
 7   Experience_Years    47 non-null     float64
 8   City                49 non-null     object
 9   State               46 non-null     object
 10  Education           49 non-null     object
 11  Performance_Rating  45 non-null     float64
 12  Joining_Date        48 non-null     object
 13  Projects_Completed  48 non-null     float64
 14  Overtime_Hours      48 non-null     float64
dtypes: float64(6), object(9)
memory usage: 5.9+ KB

In [57]:
df.shape

(49, 15)

In [58]:
df.dtypes

Employee_ID            object
Name                   object
Age                   float64
Gender                 object
Department             object
Position               object
Salary                float64
Experience_Years      float64
City                   object
State                  object
Education              object
Performance_Rating    float64
Joining_Date           object
Projects_Completed    float64
Overtime_Hours        float64
dtype: object